app:
  # app run port
  port: 8080
  pprof_port: 8090
  app_env: "local"
  app_debug: true
  app_name: "news"
  graceful_wait: 5s

# db config
db:
  user: "root"
  password: "liwentao"
  host: "127.0.0.1"
  port: "3306"
  dbname: "go-api"