package main

import (
	"log"

	"github.com/liwentao0503/go-api/internal/api"
	"github.com/liwentao0503/go-api/internal/providers"

	// docs is generated by Swag CLI, you have to import it.
	_ "github.com/liwentao0503/go-api/docs"
)

func main() {
	var app api.NewsHandler
	// dependency injection
	if err := providers.Inject(&app); err != nil {
		log.Fatalf("provier error:%s\n", err)
	}

	// app cmd service run
	app.RunCMD()

	// app cmd service run
	app.Run()
}
