package main

import (
	"log"

	"go-api/internal/api"
	"go-api/internal/providers"

	// docs is generated by Swag CLI, you have to import it.
	_ "go-api/docs"
)

func main() {
	var app api.NewsHandler
	// dependency injection
	if err := providers.Inject(&app); err != nil {
		log.Fatalf("provier error:%s\n", err)
	}

	// app cmd service run
	// go app.RunCMD()

	// app cmd service run
	app.Run()
}
